### ISSUE TITLE
Mod Missing on Steam / Mac OS

### ISSUE THREAD

**Issue by AlakhaiVaynard** [minusnolldag/archaeology-skill#2]
I'm having some weird behavior with this mod - I am on a MacBook using the Steam version of the game, and the mod doesn't show up at all even though it is installed.  If I switch to Chrome, the mod works fine.  But anytime I switch back and forth it resets my progress as if I had reinstalled (which makes a little bit of sense, since the Steam/Mac version doesn't appear to be noticing it at all).  I'd like to think I am missing something but once I got to the point of literally being able to swap back and forth with my mods all installed, it seems like my options are limited!
<img width="250" alt="Screenshot 2023-08-02 at 8 56 59 AM" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/9ad792d1-a5f7-4306-89cc-ca5697c6a4f4">
<img width="786" alt="Screenshot 2023-08-02 at 8 54 24 AM" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/6a51a95d-2240-4505-8118-fe5f4d064c1d">

Even more strange, I can literally watch the book pop in and out of my inventory, on Steam the space is just empty, and if I login on Chrome it has the book there (in addition to already appearing in my Lore section).  If I sell the book, login on Mac, then login back on Chrome it gives me another copy (again, as if I had just reinstalled the mod).  Let me know if you want anymore details!  I decided not to level up the skill just yet (prefer playing on Steam so I don't lose background progress accidentally when another window is in front).

**Comment by AlakhaiVaynard** [comment]
Should have added, I can

**Comment by minusnolldag** [comment]
Hey [AlakhaiVaynard](https://github.com/AlakhaiVaynard),
I don't have the steam version but as all versions load the same code it should be the same. I will do my best to help.

In the photos is this just on the browser or also seen on Steam? Can you confirm Steam has the mod loaded as well.


Like this:
<img width="788" alt="Screen Shot 2023-08-06 at 2 03 45 pm" src="https://github.com/minusnolldag/archaeology-skill/assets/45910931/e5357ad2-3fa7-4b64-82fd-7e57c5a35ad3">

When I have the mod installed with Chrome and then I use the Melvor Idle app on the iPhone it doesn't automatically load the mod. Then when loading my save it doesn't load the mod (because the mod is not loaded), Melvor then saves the game, finally going back to the browser now loads the mod but as a first load (this is intended logic i.e. if you load the same save without the mod loaded, the mods load function doesn't get called which overwrites the save without the mod data).

If the mod is installed on the steam version, can you please install [dev.Console](https://mod.io/g/melvoridle/m/devconsole) and press Shift + \`. Enter `game.archaeology.id` and it should return `archaeology_skill:Archaeology`. If it returns `TypeError: Cannot read properties of undefined (reading 'id')` then the mod isn't loaded into the game.

Thanks

**Comment by AlakhaiVaynard** [comment]
The first screenshot was the browser, second was Steam.  I actually already had dev.Console don't know why I didn't think about capturing the log output from when it first loaded.  But now I did, and it seems like this is the issue I'd imagine:

<img width="637" alt="Screenshot 2023-08-06 at 9 54 50 AM" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/04b41601-6209-4871-9d03-1638dd55eb3f">

Not quite certain why there would be a reserved word on the Steam/Mac client and not on the chrome client.  I don't have the time right this minute but I can try debug down further and see if I can't figure out what the actual reserved word is.  Might be as simple as renaming a variable to something my MacBook doesn't hate.

The most common one I see on Google is 'await' but that seems odd, because I'd expect that to consistently error in other implementations.

**Comment by AlakhaiVaynard** [comment]
For what it is worth, it does seem to be the usage of await that is probably causing the issue, but it is weird that it only happens on my Steam client, even on the same machine.  Even more curious, I wondered if it was a bug/issue in WebKit (I am using Chrome as my web browser, which no longer uses Webkit, I'm not sure what the Steam client was using underneath but it seemed reasonable to expect OS default) so I tried Safari, and it works fine there too.  I'll see what else I can find, now I'm super interested.

**Comment by minusnolldag** [comment]
Thanks for the photo that helps a lot. The mod is trying to call some await code but it is not in a async function. [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) is the docs if you're interested.
```js
export async function setup() {
	console.log("Registering Patch Data");
	await loadModule("assets/js/patch.mjs"); // Here
	console.log("Loading Archaeology Module"); // Since this is not seen in the log output
}
```

```js
// In patch.mjs I have this code (note not in a async function)
const { loadModule } = mod.getContext(import.meta);
await loadModule("assets/js/patches/game.mjs");
// ... more code
```

Is was lazy programming by me. I will fix it asap.

**Comment by AlakhaiVaynard** [comment]
Glad I could help!  Interesting that other implementations seem to figure it out. I guess probably because, in context, the calls inside patch.mjs are called from 'setup' which is marked async.  Wonder why the Mac wrapper client is being so picky.  But perhaps a question for another day.

**Comment by minusnolldag** [comment]
I believe I have fixed this issue now, had to recode a lot of files but the update is here d32a2aa. Before closing this issue could you test the newest version for me using the Creator Toolkit.

Here is the file - [archaeology-skill.zip](https://github.com/minusnolldag/archaeology-skill/files/12290279/archaeology-skill.zip)

If you haven't used the Creator Toolkit before, use these steps to help:
1. Disable Archaeology Skill in the Mod Manager
2. Subscribe to the Creator Toolkit in the Mod Manager
3. Reload Steam to load the Creator Toolkit
4. Click the * in the Mod Manager
5. Click Local Mods
6. Click Add
7. Enter a name and choose the zip file
8. Click Save
9. Reload Steam

Cheers!

**Comment by AlakhaiVaynard** [comment]
Alright, I am pretty confident I did this right, I think the MacOS Steam client is just being a real **bleep** about it still.

Creator Toolkit Setup

<img width="1569" alt="ModSetup" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/d0f924e7-699b-46c1-9551-e5361f2e16e0">

Creator Toolkit Setup 2

<img width="1587" alt="ModManifest" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/536506be-489f-45ab-8556-2a5013639028">

My other mods - I went ahead and disabled everything except the console for the test

<img width="926" alt="ModList" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/0f171ed8-83a7-494b-bfdb-89da02c11739">

The log output (nothing from Archaeology?)
<img width="414" alt="LogOutput" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/cab15e30-e86f-4aba-b5bd-04819060f017">

So, then I tried it on my a PC I have using steam.  Worked fine (though I'll note, there was still no log output which seemed odd - I can see the log statements in the code).  Then, out of curiosity I checked the mod.io version on that same PC, and it also worked fine.  So, potentially an invalid test.  Dug around a bit, and saw Directory Link for the Steam client, figured I'd give that a shot and I get this error:

<img width="1177" alt="DirectoryLink" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/4d540e35-684c-4945-b661-cfe920da635e">

So then because this is so much fun... I created a blank, new empty mod using the 'Getting Started' boilerplate code

<img width="1166" alt="StillNoManifest" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/894e3844-4088-4e99-ae81-6e6f98ce7e9c">

Alright fine, zip that up...
<img width="1181" alt="MyModZipped" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/d1b70c66-f9dc-460c-866b-7d72763c725e">

And... I don't get any output from that in the dev.Console either.

**Comment by AlakhaiVaynard** [comment]
Sigh, hit post and had a thought, I think I just realized why that is. I tried it in the browser, and it is because the Creator Toolkit is forced to load first, which means dev.Console isn't loaded.  I'll download the zip for that and install it via Creator Toolkit so it can load first and get you some more info soon.

**Comment by AlakhaiVaynard** [comment]
Alas: 

<img width="794" alt="StillUpset" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/b613d015-e4f2-4552-aabd-3a5e1af6307c">

But at least now I have that setup for a testing pipeline.

**Comment by AlakhaiVaynard** [comment]
Looks like:

js/menus/archaeology_menu.mjs
js/menus/arcanum_obelisk_menus.mjs

both have unwrapped await calls at the top.  I may have some time later I can try to fork on my own and work through these now that I'm following the basics.  I'll put a comment here if I do that so we don't bump heads.

**Comment by minusnolldag** [comment]
Hey at least we found the the Steam client is more strict than a browser lol

**Comment by minusnolldag** [comment]
Ok I have gone through every file so hopefully I got it this time. Commit is at de9aad6
Could you try this one for me please? [archaeology-skill.zip](https://github.com/minusnolldag/archaeology-skill/files/12296919/archaeology-skill.zip)

**Comment by AlakhaiVaynard** [comment]
![image](https://github.com/minusnolldag/archaeology-skill/assets/20563305/c7afa606-6399-42b8-8071-ee7db70bf700)

<img width="495" alt="Screenshot 2023-08-08 at 10 03 34 PM" src="https://github.com/minusnolldag/archaeology-skill/assets/20563305/36e8e640-a47f-43fe-8329-470671d76c4e">


After the screenshot I clicked the book and that did unlock it.  I was using a test account though so I couldn't make a Mattock but I feel like it definitely registered and seemed good to go.

Thanks!

**Comment by minusnolldag** [comment]
Awesome, that is great to hear! I will update Mod.IO now.

Thank you for your help!
